drop table if exists geoname;
create table geoname (
	id int default null,
	name varchar(200) default null,
	asciiname varchar(200) default null,
	alternatenames varchar(10000) default null,
	latitude double default null,
	longitude double default null,
	feature_class char(1) default null,
	feature_code varchar(10) default null,
	country_code char(2) default null,
	cc2 varchar(200) default null,
	admin1_code varchar(20) default null,
	admin2_code varchar(80) default null,
	admin3_code varchar(20) default null,
	admin4_code varchar(20) default null,
	population bigint default null,
	elevation int default null,
	dem int default null,
	timezone varchar(40) default null,
	modification_date text default null,
	index (feature_class),
	index (admin1_code),
	index (admin2_code),
	index (admin3_code),
	index (admin4_code),
	index (country_code, feature_code)
) engine = InnoDB default charset = utf8mb4 collate = utf8mb4_general_ci